import { Concat as concat } from './src/concat';
import { FillForm as fillForm } from './src/fillform';
import { FDFGenerator as generator } from './src/fdf-generator';
import { setup as binaryPath } from './src/setup';
import { Fix as fix } from './src/fix';
import { Rotate as rotate } from './src/rotate';
import { Sign as sign } from './src/sign';
import { Stamp as stamp } from './src/stamp';
export declare const Concat: typeof concat, FillForm: typeof fillForm, FDFGenerator: typeof generator, PdfData: typeof generator._extractFieldNames, setup: typeof binaryPath, Fix: typeof fix, Rotate: typeof rotate, Sign: typeof sign, Stamp: typeof stamp;
export declare type FilePath = string;
